kadinsky:
  api:
    key:
    secret:
    endpoint:
      url: https://api-key.fusionbrain.ai/
      style_url: cdn.fusionbrain.ai/static/styles/api
      status_path: /key/api/v1/text2image/status/
      service_available_path: /key/api/v1/text2image/availability
      generate_path: key/api/v1/text2image/run

server:
  port: 8090